### ISSUE TITLE
can't establish a connection to the server at localhost:4000.

### ISSUE THREAD

**Issue by Francisjpll** [nextstrain/tb#6] opened 2020-07-04 13:21 UTC
Dear nexstrain team

I am trying to reproduce the TB tutorial,  I wanted to visualize tb.json within the auspice folder. I tried to visualize it by using auspice conda env  

**Current Behavior**  
Unable to connect  http://localhost:4000

**Expected behavior**  
 visualize tb.json by using auspice conda env

  
**Your environment: if running Nextstrain locally**  
 - Operating system:  Linux 3.19.0-80-generic x86_64
 - Browser:  firefox  and  google chrome 
 - Version (e.g. `auspice 2.7.0`):  2.17.1
![Picture1](https://user-images.githubusercontent.com/44403340/86513232-c3126580-be08-11ea-93a0-efca14ed4dd1.png)
![Picture3](https://user-images.githubusercontent.com/44403340/86513237-cc033700-be08-11ea-8398-8696d3d66c73.png)

many thanks in advance

Johanna

**Comment by jameshadfield** [comment] 2020-07-15 05:26
In the terminal output from `auspice view --datasetDir auspice` the message "Looking for datasets in undefined" seems problematic. It should indicate something like "Looking for datasets in <some path>/auspice". Could you ensure that there is a directory called "auspice" you are running the command in, or else change the path you're supplying to the `--datasetDir` argument. 

That being said, I  wouldn't expect this to result in an "unable to connect" error, assuming the `auspice view` command hasn't exited or been closed. Could you try running `curl http://localhost:4000` in a terminal (while the `auspice view ...` command is still running in a separate terminal) and paste the output here?

**Comment by guillemmasfiol** [comment] 2020-10-27 13:36
Hello James,

I also encounter this problem as FJohanna_Perez. I ran nextstrainZika tutorial in a unix-based machine using conda until summarizing the results into the auspice/zika.json .

Then I use auspice in the same nextstrain conda environment, where I had installed auspice using 
npm install --global auspice

Even though it seems that auspice recognizes the directory and the files, but then I can't retrieve anything from http://localhost:4000


![localhost](https://user-images.githubusercontent.com/68853121/97300311-90c4c200-1856-11eb-9fc7-a01f357c9ea5.png)


I tried running in a separate terminal while auspice was running and this is what I got:

curl http://localhost:4000
<!doctype html><html><head><title>auspice</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" href="/favicon.png" type="image/png"><link rel="icon" href="/favicon.png" type="image/png"></head><body class="viewport"><div id="root"></div><script src="/dist/auspice.chunk.core-vendors.bundle.5465284e99792a9594d0.js"></script><script src="/dist/auspice.bundle.898717dd634e7e53dcfb.js"></script></body></html>[

Thank you very much in advance,

Guillem

**Comment by jameshadfield** [comment] 2020-10-27 20:20
The output from `curl http://localhost:4000` looks good to me, which indicates that the auspice server (which is running via the `auspice view ...` command) is working as expected and. This would seem to point to the browser being the issue, or some sort of local configuration issue. Could you try using different browsers and see if that changes anything? cc the linux experts @tsibley @ivan-aksamentov who may know more!

**Comment by guillemmasfiol** [comment] 2020-11-12 17:18
Could it perhaps be a problem encountered when running such interactive tools from remote environments (i. e. servers systems elsewhere), specially when we need to run computationally intensive or time consuming taks.

I just found this page where they provide possible ways to overcome this sort of problems, so being able to open on "local" browser things that are running on the server side:

[http://merenlab.org/2018/03/07/working-with-remote-interative/](url) 

Best,

Guillem

**Comment by Francisjpll** [comment] 2020-11-13 07:53
Dear all,

Sorry I have been out of the loop with this. But I remember I was trying it by using a VPN connection and I was wondering whether it can be related to that.   Many thanks for the input!

Best,

Johanna

**Comment by tsibley** [comment] 2020-12-17 00:37
@Francisjpll A VPN could indeed cause such issues, although usually VPNs don't mess with network traffic to `localhost`.

@guillemmasfiol Your suggestion is correct that accessing `localhost` when running `auspice view` / `nextstrain view` on a remote computer/server won't work. `localhost` in that case must be replaced by the hostname of the remote computer, but firewalls also come into play so even that will likely not work by default. It's not clear to me if remote computers are involved in this issue or not.

**Comment by genehack** [comment] 2024-08-14 17:02
Looks like this was intended to be closed but Tom's comment inadvertently re-opened it — closing it again.

**Closed by genehack** 2024-08-14 17:02 UTC
Labels: bug
